package openapi

import "strings"

// maxRefDepth guards against a $ref cycle (A points at B points at A)
// sending the resolver into infinite recursion on a malformed document.
const maxRefDepth = 12

// resolveRef follows one local JSON Pointer ("#/components/schemas/User",
// OpenAPI 3; "#/definitions/User", Swagger 2) within doc. External refs
// (a different file or URL) are intentionally not supported — SSGhost666
// works from a single document, which covers the overwhelming majority of
// real-world OpenAPI/Swagger files, including ones generated by tooling
// that bundles everything into one file.
func resolveRef(doc M, ref string) (M, bool) {
	if !strings.HasPrefix(ref, "#/") {
		return nil, false
	}
	var cur interface{} = doc
	for _, raw := range strings.Split(strings.TrimPrefix(ref, "#/"), "/") {
		seg := unescapeJSONPointer(raw)
		m, ok := cur.(M)
		if !ok {
			return nil, false
		}
		cur, ok = m[seg]
		if !ok {
			return nil, false
		}
	}
	m, ok := cur.(M)
	return m, ok
}

func unescapeJSONPointer(s string) string {
	s = strings.ReplaceAll(s, "~1", "/")
	s = strings.ReplaceAll(s, "~0", "~")
	return s
}

// resolveSchema fully resolves a schema node: follows $ref (recursively —
// a $ref can point at another $ref, or at a schema that itself uses
// allOf), and flattens allOf by merging every branch's "properties" into
// one map. The result carries "properties" (merged) plus, where present,
// "type", "example" and "default" from whichever branch set them last —
// enough to drive parameter/body fuzzing without implementing the full
// JSON Schema spec (oneOf/anyOf/not and cross-file $ref are intentionally
// out of scope: SSGhost666 fuzzes fields, it doesn't validate documents).
func resolveSchema(doc M, schema interface{}, depth int) M {
	if depth > maxRefDepth {
		return M{}
	}
	sm, ok := schema.(M)
	if !ok {
		return M{}
	}

	if ref, ok := sm["$ref"].(string); ok {
		target, found := resolveRef(doc, ref)
		if !found {
			return M{}
		}
		return resolveSchema(doc, target, depth+1)
	}

	merged := M{}
	mergedProps := M{}

	if allOf, ok := sm["allOf"].([]interface{}); ok {
		for _, sub := range allOf {
			subResolved := resolveSchema(doc, sub, depth+1)
			if subProps, ok := subResolved["properties"].(M); ok {
				for k, v := range subProps {
					mergedProps[k] = v
				}
			}
			for _, k := range []string{"type", "example", "default"} {
				if v, ok := subResolved[k]; ok {
					merged[k] = v
				}
			}
		}
	}

	if props, ok := sm["properties"].(M); ok {
		for k, v := range props {
			mergedProps[k] = v
		}
	}
	for _, k := range []string{"type", "example", "default"} {
		if v, ok := sm[k]; ok {
			merged[k] = v
		}
	}

	if len(mergedProps) > 0 {
		merged["properties"] = mergedProps
	}
	return merged
}

// resolveParamObj resolves a parameter entry that may itself be
// {"$ref": "#/components/parameters/Foo"} instead of an inline object —
// legal in both OpenAPI 3 and Swagger 2, and common in documents that
// factor shared parameters out to avoid repetition.
func resolveParamObj(doc M, param interface{}, depth int) M {
	if depth > maxRefDepth {
		return nil
	}
	pm, ok := param.(M)
	if !ok {
		return nil
	}
	if ref, ok := pm["$ref"].(string); ok {
		target, found := resolveRef(doc, ref)
		if !found {
			return nil
		}
		return resolveParamObj(doc, target, depth+1)
	}
	return pm
}
